inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - Rakefile

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
