sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - tmp/cache/assets/test
addons:
  postgresql: '9.4'
services:
- redis-server
- postgresql
before_install:
- gem update --system
- gem install bundler -v 1.16.2
before_script:
  - "./bin/rake db:create db:migrate RAILS_ENV=test"
notifications:
  slack:
    secure: DW0oiyRssocBQPz2nFHfwSZRRqe4SzO0mTlnAz6G00qlwLHeRCV5A+OLC87QdIRFVn4PXGrkYj4ioivkXNNmCqKR9/XKpWkKZ2JHItTj5l7FJvvP7kVwZsX0BdtK/S4VYZQQ10Z7G1VHs7EUREZrDOXEVjX4JzB4DDFy73POWD9f360Rz9yVzhE20kICesa9doKGXIdcub5j0vc1PsaxvT4oc3Ur++C2ZfpuwyBjjPlG4itoMZySQZFtWviq4Cmu4Z4uPXx0cBYLx9Z7gwlAxsCT4FfRNtvrQgZn7f6fdseq2c5KMkjyFwbNreh1P/71Jf1UyVNPwdXynjNcIHA/80i6Ho7BgKf6LHYO6gQYqB/RVeFBtgLzD0g6AlsZ/1gS2jcfKKaZbIIa8X0YV2i7usPcerr0HMUIdnrynH49ekWB+hAe5iQOS0a5Hugi+WjhWWslF32d+wWFczh0uo3oFwY8RlKcgjkk/wRBZTG4jyjbQd32aMzMCxE/BDFL2JRrY7ZgURMCungAfOQ9KQw4mdVvQMJ1wrSy94XSwc6dkbN2ef3XNXQNWUmwBND6iguvsMUXtGpsWl9B0bqKO9EHCsn8XWIrK3XzxC4B5XsZLn/th5jeQsoIO2sIALq6FQL3ifGtP9Vq/gMMDhsNxwLCtkvGrAY6a1tI8dIjFC19+6g=
