default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_POOL', ENV.fetch('RAILS_MAX_THREADS', 5)) %>

development:
  <<: *default
  database: reporting_development

test:
  <<: *default
  database: reporting_test

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
